### ISSUE TITLE
可不可以加个循环啊

### ISSUE THREAD

**Issue by dangshi** [buppt/electron-vue-music#8]
老哥太强了

**Comment by buppt** [comment]
哈哈哈，我尽快

**Comment by buppt** [comment]
已经加上了

**Comment by dangshi** [comment]
谢谢，太赞了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "【意涵团】buppt"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 中午11:01
收件人: "buppt/electron-vue-music"<electron-vue-music@noreply.github.com&gt;; 
抄送: "兰云飞"<869125870@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [buppt/electron-vue-music] 可不可以加个循环啊 (#8)





 
已经加上了
